import type { Metadata } from "next";
import {Alata, Andika, Russo_One, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import Sidebar from "@/components/Sidebar";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const alata = Alata({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-Alata',
});

const RussoOne = Russo_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-Russo_One',
})

const Andika_ = Andika({
  weight: '400', // or an array like ['400', '700'] if you need more
  subsets: ['latin'],
  variable: '--font-Andika',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
    <html
      lang="en"
      className={cn("h-full", "antialiased", alata.variable, RussoOne.variable, Andika_.variable, "font-mono", jetbrainsMono.variable)}
    >
      <body className="min-h-full flex flex-col">
      <div className="h-screen bg-white flex">
        <Sidebar/>
        {children}
      </div></body>
    </html>
      </ClerkProvider>
  );
}
