import type { Metadata } from "next";
import {Alata, Andika} from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";

const alata = Alata({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-Alata',
});

const Andika_ = Andika({
  weight: '400', // or an array like ['400', '700'] if you need more
  subsets: ['latin'],
  variable: '--font-Andika',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
    <html
      lang="en"
      className={`${alata.variable} ${Andika_.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <div className="h-screen bg-white flex">
        {children}
      </div></body>
    </html>
      </ClerkProvider>
  );
}
